name: Deploy Solution to Dev Environment

on:
  push:
    branches:
      - feature/master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20.x

      - name: Run npm ci
        run: npm ci

      - name: Bundle & Package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: Debug File Path
        run: ls -R sharepoint/solution

      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2.2.4
        with:
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT_ID }}
        env:
          M365_CLIENT_ID: ${{ secrets.APP_ID }}
          M365_CLIENT_SECRET: ${{ secrets.CERTIFICATE_PASSWORD }}
          M365_TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Deploy App to DEV Site Collection App Catalog
        id: devDeploy
        uses: pnp/action-cli-deploy@v4.0.0
        with:
          APP_FILE_PATH: sharepoint/solution/pitchers.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true
          SCOPE: sitecollection
          SITE_COLLECTION_URL: https://piindext.sharepoint.com/sites/AppDev